
//PRODUCTOS

POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "name": "bicicleta",
    "description": "Galletitas ricas",
    "price": 550,
    "stock": 20
}

###

GET http://localhost:3000/api/usuarios

###

DELETE http://localhost:3000/api/productos/6554a1437a064c358bc53196

###

//USUARIOS Y SUS TIPOS

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "mail": "asd@gmail.com",
    "password": "asd"}

###

GET http://localhost:3000/api/usuarios/

###

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "mail": "mail@gmail.com",
    "password": "asdasd"
}
